$modelname    "props/poolhalls/ball.mdl"
$body         ball "ball.dmx"
$surfaceprop  Gmod_Ice
$sequence     idle "ball.dmx"
$cdmaterials  "models/poolhalls"
$collisionmodel "ball.dmx" {
    $mass   0.5
}
$texturegroup ball {
    { ball-cue }
    { ball-1 }
    { ball-2 }
    { ball-3 }
    { ball-4 }
    { ball-5 }
    { ball-6 }
    { ball-7 }
    { ball-8 }
    { ball-9 }
    { ball-10 }
    { ball-11 }
    { ball-12 }
    { ball-13 }
    { ball-14 }
    { ball-15 }
}
